### ISSUE TITLE
Link about to break

### ISSUE THREAD

**Issue by markstos** [jayseae/Refeed-Lite-Redux#1]
The blog post linked to my site is going away. You can get the content from the Wayback machine, or copy/paste it somewhere.

https://web.archive.org/web/20150911052156/http://mark.stosberg.com/blog/2008/09/refeed-lite-a-movable-type-plugin-to-republish-feeds.html

**Comment by jayseae** [comment]
Thanks for the update, Mark. I have updated the description and the URI to point to the Wayback Machine instead of your site.
